
- name: A playbook to install Kubectl, Minikube
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: 1. Update APT Package Manager
    apt:
      update_cache: yes
  - name: 2. Install Apt install https
    apt:
      update_cache: yes
      name: apt-transport-https
  - name: 3. Curl
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - name: 4. Echo
    shell:
      cmd: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - name: 5. Update APT Package Manager
    apt:
      update_cache: yes
  - name: 6. Install kubectl
    apt:
      update_cache: yes
      name: kubectl



